FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY CDataProc /CDataProc
COPY config.ini /CDataProc/

WORKDIR /CDataProc
CMD ["python", "CDataProc.py", "config.ini"]