FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY CDataComparator /CDataComparator
COPY config.ini /CDataComparator/

WORKDIR /CDataComparator
CMD ["python", "CDataComparator.py", "config.ini"]