version: '3.4'

services:
  su-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: su-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000

  su-broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: su-broker
    restart: always
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9192:9192"
    depends_on:
      - su-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'su-zookeeper:2183'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://su-broker:9192,PLAINTEXT_INTERNAL://su-broker:29192
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./Dockerfile.monitor
    depends_on:
      - su-broker

  sensor:
    image: sensor
    build:
      context: .
      dockerfile: ./Dockerfile.sensor

  scada:
    image: scada
    build:
      context: .
      dockerfile: ./Dockerfile.scada
    ports:
      - "6069:6069"   

  device:
    image: device
    build:
      context: .
      dockerfile: ./Dockerfile.device
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - ./storage/:/storage
    ports:
      - "6064:6064"

  protection:
    image: protection
    build:
      context: .
      dockerfile: ./Dockerfile.protection_system
    ports:
      - "6068:6068"

  file_server:
    image: file_server
    build:
      context: .
      dockerfile: ./Dockerfile.file_server    
    volumes:
      - ./file_server/data/:/file_server/data
    ports:
      - "6001:6001"

  CDataInput:
    image: cdatainput
    build:
      context: .
      dockerfile: ./Dockerfile.CDataInput
    ports:
      - "6011:6011"

  CDataProc:
    image: cdataproc
    build:
      context: .
      dockerfile: ./Dockerfile.CDataProc

  FakeCDataProc:
    image: fakecdataproc
    build:
      context: .
      dockerfile: ./Dockerfile.FakeCDataProc

  CDataComparator:
    image: cdatacomparator
    build:
      context: .
      dockerfile: ./Dockerfile.CDataComparator

  CDataOutput:
    image: cdataoutput
    build:
      context: .
      dockerfile: ./Dockerfile.CDataOutput

  CDataSign:
    image: cdatasign
    build:
      context: .
      dockerfile: ./Dockerfile.CDataSign

  CDataVerifySign:
    image: cdataverifysign
    build:
      context: .
      dockerfile: ./Dockerfile.CDataVerifySign