FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY CDataInput /CDataInput
COPY config.ini /CDataInput/

WORKDIR /CDataInput
CMD ["python", "CDataInput.py", "config.ini"]