FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY CDataSign /CDataSign
COPY config.ini /CDataSign/

WORKDIR /CDataSign
CMD ["python", "CDataSign.py", "config.ini"]