FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY FakeCDataProc /FakeCDataProc
COPY config.ini /FakeCDataProc/

WORKDIR /FakeCDataProc
CMD ["python", "FakeCDataProc.py", "config.ini"]